### ISSUE TITLE
Performance monitoring with Sentry

### ISSUE THREAD

**Issue by tnguyen21** [sharingexcess/rescue#119]
I think it'd be valuable if we leverage some of the performance monitoring functions in Sentry. So far, one of the test drivers had issues with long initial load times for the application. In the next few days, we'll see if this is a recurring issue for drivers.

I'd want to try logging some performance data to build an understanding of what's the bottleneck, and what we might be able to do to address it.

**Comment by ryanmchenry2** [comment]
@tnguyen21 Checking in on this - was there a decision made on this front?

**Comment by nhatduy227** [comment]
Sentry is added to the codebase
