### ISSUE TITLE
Phone number formatting utility

### ISSUE THREAD

**Issue by tnguyen21** [sharingexcess/rescue#149]
Our utility for parsing and formatting phone numbers doesn't really handle edge cases. For example, if a user includes an area code in the phone number, then the phone number isn't parsed correctly and doesn't get rendered.

For example: 
![image](https://user-images.githubusercontent.com/19523341/109548154-e7a30800-7a91-11eb-8f12-5cc5f85c556b.png)
phone number is rendered
![image](https://user-images.githubusercontent.com/19523341/109548205-f7225100-7a91-11eb-984e-de63710e12ca.png)
phone number is in expected format on form

---
![image](https://user-images.githubusercontent.com/19523341/109548241-03a6a980-7a92-11eb-983c-e3ef4ea086f8.png)
Phone number includes area code on form
![image](https://user-images.githubusercontent.com/19523341/109548303-191bd380-7a92-11eb-88cf-9bb403f196ef.png)
phone number not rendered properly

**Comment by nhatduy227** [comment]
This issue is resolved
