### ISSUE TITLE
Add a license to the project

### ISSUE THREAD

**Issue by blackgirlbytes** [sharingexcess/rescue#334]
This project needs licensing to better meet Open Source community standards. I will research the difference licenses and add a license to this project.

**Comment by ryanmchenry2** [comment]
Hey Rizel! Just checkin in to see if I can help on this, or if you want to setup time to talk more

**Comment by blackgirlbytes** [comment]
@ryanmchenry2 I was going to tackle this one after my prior PRs got reviewed!!! I sent you a slack message
