### ISSUE TITLE
Create Figma Design for Bulk Pickup tool

### ISSUE THREAD

**Issue by ryanmchenry2** [sharingexcess/rescue#360]
On the `Pickup Report` page, the button at the top to open our new modal should read "Open Bulk Input Tool". Inside the modal should be fairly straightforward to style, but for sake of best practices, let's make a brief figma design for it first to put it in front of Evan and Jacob!

**Comment by samnguyen102** [comment]
![image](https://user-images.githubusercontent.com/60908199/145274999-257e10c9-4ae5-4cb7-bce1-36684d2ba027.png)
