### ISSUE TITLE
Persist data in the pickup report when phone sleeps

### ISSUE THREAD

**Issue by gallexi** [sharingexcess/rescue#362]
# Background

Evan and Jacob have [reported that](https://sharingexcess.slack.com/archives/C02AU8A37AQ/p1640273304004300), if they're mid-pickup (and have typed some numbers into the pickup report), and the phone snoozes due to inactivity, it clears all the numbers that they've entered by the time they re-open the app.

![Pickup report with no data in the fields](https://user-images.githubusercontent.com/17116584/147279284-45720608-1c70-489a-8c48-38298c86613a.png)

# Actual behavior
When the phone goes to sleep before the driver saves the report, the numbers are cleared from the report so the driver has to start over.

# Expected behavior
The numbers are still in the boxes, even if they don't click "save". This will probably be something like "client-side temporary persistence", so whoever takes this ticket might start by googling something like that =]

# Current workarounds
Jacob reports "Safest thing to do is submit the report and then update it every time you have more numbers"

# Open questions
- Are there other fields in the app that have this issue?

**Comment by ryanmchenry2** [comment]
Let's definitely work on this!

We can accomplish this by saving the `formData` to `sessionStorage` (this is one of the browser's storage mechanisms). Here's some rough pseudocode to get you going in the right direction...
```
// handle storing formData every time it's updated
useEffect(() => {
  const formDataString = JSON.stringify(formData)
  window.sessionStorage.setItem(`pickup_report_${stop_id}`, formDataString)
}, [formData])

// handle populating formData on page load
useEffect(() => {
  const savedFormData = window.sessionStorage.getItem(`pickup_report_${stop_id}`)
  if (savedFormData) {
    setFormData(JSON.parse(savedFormData))
  }
}, [])
```

We'll need to make sure this doesn't interfere with populating `formData` for a previously completed pickup with data from the database.
