### ISSUE TITLE
Configure Protected Production Deploys on Github Actions

### ISSUE THREAD

**Issue by ryanmarshallmc** [sharingexcess/rescue#370]
Currently, production deploys are done manually using `scripts/prod_deploy.js`. Let's configure automated deployment with Github Actions for the production environment. Prod deploys should require approval by an admin (for now that should be me) before they go through. We also need to confirm that all environment variables are populated in the `prod` environment with Github secrets to ensure the build environment has all necessary data.

**Comment by scottmc500** [comment]
Looks like we can't stop a pipeline run in the middle to request approval.  Bummer.

"There is currently no feature that allows prompting for manual input during workflow runs. See this response on the community forums where a similar question was asked.

Here are some options you can explore:

- Redesign the scripts to read from configuration files and check them into git to trigger the build.

- Use the workflow_dispatch event to create a workflow that you can manually trigger from the Actions UI and supply input parameters. See this documentation for more detail.

- Use slash-command-dispatch to trigger the build using a slash command with arguments for the build's input parameters."

https://stackoverflow.com/questions/63252525/how-can-i-automate-a-usually-interactive-build-script-with-github-actions

**Comment by ryanmarshallmc** [comment]
Hey @scottmc500 can I get an update on this? Is the comment above the most up to date? I remember seeing a feature in the past that you can configure an environment to require approval for any actions to run, and that might be setup in our "prod" env config already.

**Comment by ryanmarshallmc** [comment]
https://github.com/sharingexcess/rescue/settings/environments/84955987/edit

**Comment by ryanmarshallmc** [comment]
As a follow up, we additionally need to update the existing deploy strategy to also include deploying Firebase Functions. Individually, this would be with the command `firebase deploy --only functions`, but could maybe be incorporated in a single deploy command. Let me know your thoughts! Worth considering how we would want this to fail gracefully if one or the other command failed for some reason
