### ISSUE TITLE
Update + Supplement Github Wiki

### ISSUE THREAD

**Issue by ryanmarshallmc** [sharingexcess/rescue#386]
Our Wiki was largely out of date from previous co-op cycles and code states. I cleaned out pages that were no longer accurate or relevant, and now our Wiki is looking pretty lean. With that said, our README is a *thiq* boi, and maybe too long as is! Can we start by migrating the core information to the Wiki, and then sync up on what should still stay on the README?

**Comment by ryanmchenry2** [comment]
Happy to kick this off with a quick 5-10 min dicussion on what should be documented in the first place. As always, the goal is to make the onboarding process for new co-ops or open source developers as easy as possible!

**Comment by ryanmchenry2** [comment]
@gallexi I'm going to add you to this along with Luke because you probably have the best perspective of what is needed for a fresh set of eyes on the repo!

**Comment by ryanmarshallmc** [comment]
@lukeshinnn Just documenting from our discussion:

First tangible step - create an Outline of all pages/info to build into the WIKI, and an outline for what info we want to continue to leave in the readme

**Comment by ryanmarshallmc** [comment]
https://dev.to/github/how-to-create-the-perfect-readme-for-your-open-source-project-1k69
As a reference, shoutout @blackgirlbytes ;)

**Comment by gallexi** [comment]
Hey, sorry I missed this previously! Luke and I sync'd a few weeks ago- Luke, let me know if there's anything else I can do to help! (with the caveat that my capacity is fairly low while I'm in Rwanda, but I can answer async questions!)

**Comment by lukeshinnn** [comment]
What to transfer from README to wiki (can also start this ASAP if approved):

- Best Practices (broken down into React/JS, Styling (sass/scss/design system), Environments)
- Version Control Best Practices
- Available Scripts
- Admin Access
- Deployment

**Comment by lukeshinnn** [comment]
Potential useful Wikis:

- API Documentation
- "Glossary" (includes info about stop status numbers, etc.)

**Comment by ryanmarshallmc** [comment]
@lukeshinnn this looks great, awesome start. Do you want to start outlining this in a shared google doc so that we can leave comments/revise together?
