### ISSUE TITLE
Rename primary branch as `main`

### ISSUE THREAD

**Issue by ryanmarshallmc** [sharingexcess/rescue#409]

**Comment by ryanmarshallmc** [comment]
@gallexi deferring to you on this knowing that you have some suuuuper first hand experience on the issue! Do you have any resources you'd recommend on walking through making this change? Want to make sure we're properly handling any problems that could come up with actions, local repos, etc etc

**Comment by gallexi** [comment]
Hey, thanks for tagging me!

This is GH's official guide on the subject: https://github.com/github/renaming

Tl;dr is that we built some tooling to make it (hopefully) Just Work™️ . The one thing I'd check is to see if any of our deployment scripts have the original default branch name hardcoded into them. But, as far as PR retargeting, preservation of git history, etc, it should Just Work!
