### ISSUE TITLE
Internal Research for App Landing Page

### ISSUE THREAD

**Issue by ryanmarshallmc** [sharingexcess/rescue#456]

**Comment by ryanmarshallmc** [comment]
- [ ] Talk with marketing to make sure we know any specific info, copy, or content they want on a landing page
 - [ ] For the "hero" section - we want a headline, any subtext/descirption, and any photos or videos they want to include

**Comment by samnguyen102** [comment]
Inspiration:
https://www.mural.co/
https://miro.com/
https://maze.co/
