### ISSUE TITLE
Create App Landing Page Prototype

### ISSUE THREAD

**Issue by ryanmarshallmc** [sharingexcess/rescue#457]

**Comment by samnguyen102** [comment]
First mock up
![image](https://user-images.githubusercontent.com/60908199/156910713-fc2eff39-1f0d-4a44-8d87-9078f154315c.png)

**Comment by samnguyen102** [comment]
![image](https://user-images.githubusercontent.com/60908199/156946576-8ce0cfdd-3158-4ffb-a004-50a5d0a7b1f2.png)

**Comment by samnguyen102** [comment]
![image](https://user-images.githubusercontent.com/60908199/156946593-4e9397fb-cc20-404a-8294-52fe30dcb6f6.png)
