### ISSUE TITLE
Add Retail Value and Distance to Rescue Preview Cards

### ISSUE THREAD

**Issue by armandoparra13** [sharingexcess/rescue#491]

**Comment by ryanmarshallmc** [comment]
@jiitra is going to add design screenshots to this issue when they're ready, and at that point @oroghene will go wild 👍

**Comment by jiitra** [comment]
First draft of wireframes:

- Date is moved up to above driver's name
- Added rounded icons for pickup and delivery
- Text size increase to 16px, could also be 15px or 14px if the 16px takes up too much screen space
- Sections for pickups and dropoffs are white background with 1px light grey border and a light grey drop shadow 6px blur

![Image](https://user-images.githubusercontent.com/74521649/171900398-ef0592f5-3a9a-4adc-bd90-e4684bba2146.png)

This version shows first 3 stops, then  "+X more" text for reduced content. 
![Image](https://user-images.githubusercontent.com/74521649/171900502-e226bd59-b23f-43bc-9860-65dcd75aa24a.png)

Completed route view with pounds and retail value labels
![Image](https://user-images.githubusercontent.com/74521649/171900627-0b4db6b3-9ad8-46c1-95f7-4c660f4ba295.png)
