### ISSUE TITLE
Missing a step in the Getting Started Section in ReadMe.

### ISSUE THREAD

**Issue by YTeyddie22** [sharingexcess/rescue#508]
In the Getting started section of Readme documentation, before cloning the project. I think the user should fork the project first to add to their repo

**Comment by YTeyddie22** [comment]
The documentation should involve guidelines for contributing to the project

**Comment by ryanmarshallmc** [comment]
Hi @YTeyddie22 - this repository is not meant to be forked. It's a living and growing application with associated resources and deployments.

**Comment by YTeyddie22** [comment]
Oh, Thank you for the feedback @ryanmarshallmc
